[google_oauth]
client_id = "308161352982-u2jhji1lcqqb42o7oql0me3nat6l3efp.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://kpi-test.streamlit.app"

allowed_users = [
  "life8ray@gmail.com",
  "inthing123@gmail.com",
  "leslie641230@gmail.com",
  "ainstaccc@gmail.com"
]
